AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with a custom script using CloudFormation

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init -v \
            --stack ${AWS::StackName} \
            --resource EC2Instance \
            --region ${AWS::Region}

          /opt/aws/bin/cfn-signal -e $? \
            --stack ${AWS::StackName} \
            --resource EC2Instance \
            --region ${AWS::Region}

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyEC2Role

  MyEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:GetObject'
                Resource: '*'

  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          install_and_run:
            - install
            - run
        install:
          packages:
            yum:
              httpd: []
        run:
          commands:
            01_start_httpd:
              command: service httpd start
              waitAfterCompletion: 5
            02_enable_httpd:
              command: chkconfig httpd on
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref MyInstanceProfile
      SecurityGroupIds:
        - !Ref EC2InstanceSecurityGroup

  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
