AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy RabbitMQ on an EC2 instance with open port

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

Resources:
  RabbitMQInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref RabbitMQSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y rabbitmq-server
          sudo systemctl enable rabbitmq-server
          sudo systemctl start rabbitmq-server

  RabbitMQSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RabbitMQ
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5672
          ToPort: 5672
          CidrIp: 0.0.0.0/0
