AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS ElastiCache Redis cluster with a specified node type

Parameters:
  ClusterName:
    Type: String
    Default: MyRedisCluster

  NodeType:
    Type: String
    Default: cache.t2.micro

  CacheSecurityGroupName:
    Type: String
    Default: MyCacheSecurityGroup

Resources:
  RedisCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: !Ref NodeType
      ClusterName: !Ref ClusterName
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      AutoMinorVersionUpgrade: true
      CacheSecurityGroupNames:
        - !Ref CacheSecurityGroupName

Outputs:
  RedisEndpoint:
    Description: Endpoint of the Redis cluster
    Value: !GetAtt RedisCluster.ConfigurationEndpoint.Address
