AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS ElastiCache Redis cluster with a specified node type and allow all traffic in the security group

Parameters:
  ClusterName:
    Type: String
    Default: MyRedisCluster

  NodeType:
    Type: String
    Default: cache.t2.micro

Resources:
  RedisCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: !Ref NodeType
      ClusterName: !Ref ClusterName
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      AutoMinorVersionUpgrade: true
      CacheSecurityGroupNames:
        - !Ref RedisSecurityGroup

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis cluster
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1  

Outputs:
  RedisEndpoint:
    Description: Endpoint of the Redis cluster
    Value: !GetAtt RedisCluster.ConfigurationEndpoint.Address
