AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS ElastiCache Redis cluster with a specified node type, allowing all traffic in the security group and VPC

Parameters:
  ClusterName:
    Type: String
    Default: MyRedisCluster

  NodeType:
    Type: String
    Default: cache.t2.micro

Resources:
  RedisVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis cluster
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1  # Allow all traffic

  RedisCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: !Ref NodeType
      ClusterName: !Ref ClusterName
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      AutoMinorVersionUpgrade: true
      VpcSecurityGroupIds:
        - !Ref RedisSecurityGroup

Outputs:
  RedisEndpoint:
    Description: Endpoint of the Redis cluster
    Value: !GetAtt RedisCluster.ConfigurationEndpoint.Address
